=== a-blender/cmsc420/sample-sets/part2in.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--  summer 2018   -->
    <!--    simple types    -->
    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="red"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="yellow"/>
            <xs:enumeration value="purple"/>
            <xs:enumeration value="orange"/>
            <xs:enumeration value="black"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sortType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="name"/>
            <xs:enumeration value="coordinate"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cityName">
        <xs:restriction base="xs:string">
            <xs:pattern value="[_a-zA-Z][_a-zA-Z0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <!--    <commands> attributes    -->
    <xs:attributeGroup name="commandsAttributes">
        <xs:attribute name="spatialWidth" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="spatialHeight" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="pmOrder" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:enumeration value="1"/>
                    <xs:enumeration value="3"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <!--    complex types    -->
    <xs:complexType name="emptyCommandType">
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="nameType">
        <xs:attribute name="name" type="cityName" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="cityType">
        <xs:attribute name="name" type="cityName" use="required"/>
        <xs:attribute name="x" type="xs:integer" use="required"/>
        <xs:attribute name="y" type="xs:integer" use="required"/>
        <xs:attribute name="radius" type="xs:integer" use="required"/>
        <xs:attribute name="color" type="colorType" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="roadType">
        <xs:attribute name="start" type="cityName" use="required"/>
        <xs:attribute name="end" type="cityName" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="listType">
        <xs:attribute name="sortBy" type="sortType" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="nearestType">
        <xs:attribute name="x" type="xs:integer" use="required"/>
        <xs:attribute name="y" type="xs:integer" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="rangeType">
        <xs:attribute name="x" type="xs:integer" use="required"/>
        <xs:attribute name="y" type="xs:integer" use="required"/>
        <xs:attribute name="radius" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="saveMap" type="xs:NCName" use="optional"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="saveMapType">
        <xs:attribute name="name" type="xs:NCName" use="required"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="shortestPathType">
        <xs:attribute name="start" type="cityName" use="required"/>
        <xs:attribute name="end" type="cityName" use="required"/>
        <xs:attribute name="saveMap" type="xs:NCName" use="optional"/>
        <xs:attribute name="saveHTML" type="xs:NCName" use="optional"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
    <!--    elements    -->
    <xs:element name="commands">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="createCity" type="cityType"/>
                    <xs:element name="clearAll" type="emptyCommandType"/>
                    <xs:element name="listCities" type="listType"/>
                    <xs:element name="printTreap" type="emptyCommandType"/>
                    <xs:element name="mapRoad" type="roadType"/>
                    <xs:element name="mapCity" type="nameType"/>
                    <xs:element name="printPMQuadtree" type="emptyCommandType"/>
                    <xs:element name="saveMap" type="saveMapType"/>
                    <xs:element name="rangeCities" type="rangeType"/>
                    <xs:element name="rangeRoads" type="rangeType"/>
                    <xs:element name="nearestCity" type="nearestType"/>
                    <xs:element name="nearestIsolatedCity" type="nearestType"/>
                    <xs:element name="nearestRoad" type="nearestType"/>
                    <xs:element name="nearestCityToRoad" type="roadType"/>
                    <xs:element name="shortestPath" type="shortestPathType"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="commandsAttributes"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== a-blender/cmsc420/MeeshQuest/treaptest.xml
<commands
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="part2in.xsd"
        pmOrder="3" spatialWidth="1024" spatialHeight="1024">

    <createCity id="1"  name="Chicago" y="37" x="140" radius="5" color="black"/>
    <printTreap id="2"  />
    <createCity id="3"  name="Los_Angeles" x="133" y="34" radius="5"  color="black"/>
    <printTreap id="4"  />
    <createCity id="5"  name="Paris" x="238" y="165" radius="5"  color="black"/>
    <printTreap id="6"  />
    <createCity id="7"  name="Miami" x="232" y="165" radius="5"  color="black"/>
    <printTreap id="8"  />
    <createCity id="9"  name="Atlanta" x="238" y="185" radius="5"  color="black"/>
    <printTreap id="10"  />
    <createCity id="11"  name="Boston" y="27" x="170" radius="5" color="black"/>
    <printTreap id="12"  />
    <createCity id="13"  name="Santa_Barbara" x="167" y="84" radius="5"  color="black"/>
    <printTreap id="14"  />
    <createCity id="15"  name="Taipei" x="89" y="25" radius="5"  color="black"/>
    <printTreap id="16"  />
    <createCity id="17"  name="Venice" x="212" y="65" radius="5"  color="black"/>
    <printTreap id="18"  />
    <createCity id="19"  name="Utah" x="8" y="5" radius="5"  color="black"/>
    <printTreap id="20"  />
    <createCity id="21"  name="Rome" x="2" y="5" radius="5"  color="black"/>
    <printTreap id="22"  />
    <createCity id="23"  name="Denver" x="18" y="15" radius="5"  color="black"/>
    <printTreap id="24"  />
    <createCity id="25"  name="Baltimore" x="12" y="51" radius="5"  color="black"/>
    <printTreap id="26"  />
    <createCity id="27"  name="Raleigh" x="18" y="115" radius="5"  color="black"/>
    <printTreap id="28"  />
    <clearAll id="29"/>
</commands>

=== a-blender/cmsc420/MeeshQuest/src/sample-sets/part2.public.nearestCity.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part2in.xsd"
	spatialWidth="1024"
	spatialHeight="1024"
	pmOrder="3">
 <createCity name="Baltimore" x="140" y="37" radius="0" color="black"/>
 <createCity name="Chicago" x="133" y="34" radius="0" color="black"/>
 <createCity name="New_York" x="200" y="300" radius="0" color="black"/>
 <createCity name="Zurich" x="1000" y="1000" radius="0" color="black"/>
 <createCity name="Paris" x="500" y="400" radius="0" color="black"/>
 <createCity name="Amsterdam" x="450" y="450" radius="0" color="black"/>
 
 <nearestCity x="50" y="10"/>
 
 <mapRoad start="Baltimore" end="Chicago"/>
 <nearestCity x="100" y="100"/>
 
 <mapRoad start="Chicago" end="New_York"/>
 <nearestCity x="300" y="500"/>
 
 <mapRoad start="New_York" end="Zurich"/>
 <nearestCity x="10" y="10"/>
 
 <mapRoad start="Zurich" end="Paris"/>
 <nearestCity x="1000" y="1000"/>
 
 <mapRoad start="Paris" end="Amsterdam"/>
 <nearestCity x="500" y="500"/>
 
 <saveMap name="part2.public.nearest"/>
</commands>

=== a-blender/cmsc420/MeeshQuest/src/sample-sets/part2.public.range.input.xml
<commands
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="part2in.xsd"
    spatialWidth="128"
    spatialHeight="128"
    pmOrder="3">
 <createCity name="A1" x="1" y="50" radius="0" color="black"/>
 <createCity name="A2" x="100" y="50" radius="0" color="black"/>
 <createCity name="A3" x="50" y="50" radius="0" color="black"/>
 <createCity name="A4" x="1" y="100" radius="0" color="black"/>
 <createCity name="A5" x="50" y="100" radius="0" color="black"/>
 <createCity name="A6" x="100" y="100" radius="0" color="black"/>
 <createCity name="A7" x="105" y="105" radius="0" color="black"/>
 
 <mapRoad start="A1" end="A2"/>
 <mapRoad start="A1" end="A4"/>
 <mapRoad start="A1" end="A5"/>
 <mapRoad start="A1" end="A6"/>
 
 <rangeCities x="50" y="50" radius="20" saveMap="part2.public.range.1"/>
 
 <mapRoad start="A2" end="A6"/>
 <mapRoad start="A4" end="A5"/>
 <mapRoad start="A5" end="A6"/>
 
 <rangeRoads x="100" y="100" radius="15" saveMap="part2.public.range.2"/>
 
 <mapRoad start="A6" end="A7"/>
 
 <rangeCities x="100" y="100" radius="10" saveMap="part2.public.range.3"/>
 <rangeRoads x="1" y="50" radius="5" saveMap="part2.public.range.4"/>
</commands>

=== a-blender/cmsc420/xml/part2in.xml
<commands
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="part2in.xsd"
        pmOrder="3"
        spatialWidth="512"
        spatialHeight="512">

    <createCity id="1" name="Baltimore" x="200" y="0" radius="0" color="black"/>
    <createCity id="2" name="Baltimore" x="81" y="47" radius="0"  color="black"/>
    <createCity id="3" name="Atlanta" x="100" y="0" radius="0"  color="black"/>
    <createCity id="4" name="Pittsburgh" x="300" y="0" radius="0"  color="black"/>
    <createCity id="4" name="Johnny" x="200" y="100" radius="0"  color="black"/>
    <createCity id="4" name="Amy" x="-1" y="20" radius="0"  color="black"/>
    <createCity id="4" name="Amy2" x="-1" y="-1" radius="0"  color="black"/>
    <createCity id="4" name="Amy3" x="-2" y="-2" radius="0"  color="black"/>

    <printPMQuadtree id="9"/>

    <mapCity name="Atlanta" />
    <mapCity name="Pittsburgh" />
    <mapCity name="Johnny" />

    <printPMQuadtree/>
    <clearAll/>

    <createCity id="3" name="S" x="10" y="10" radius="0"  color="black"/>
    <createCity id="4" name="B1" x="200" y="0" radius="0"  color="black"/>
    <createCity id="4" name="A1" x="0" y="100" radius="0"  color="black"/>
    <createCity id="4" name="A2" x="100" y="100" radius="0"  color="black"/>
    <createCity id="4" name="A3" x="100" y="200" radius="0"  color="black"/>
    <createCity id="4" name="E" x="200" y="200" radius="0"  color="black"/>

    <mapRoad start="S" end="A1"/>
    <mapRoad start="A1" end="A2"/>
    <mapRoad start="A2" end="A3"/>
    <mapRoad start="A3" end="E"/>
    <mapRoad start="S" end="B1"/>
    <mapRoad start="E" end="B1"/>

    <printPMQuadtree/>

    <createCity name="Z1" x="400" y="400" radius="1" color="red"/>
    <createCity name="Z2" x="350" y="360" radius="1" color="red"/>
    <createCity name="Z3" x="360" y="370" radius="1" color="red"/>
    <createCity name="Z4" x="370" y="380" radius="1" color="red"/>
    <createCity name="Z5" x="410" y="320" radius="1" color="red"/>
    <createCity name="Z6" x="290" y="405" radius="1" color="red"/>
    <createCity name="Z7" x="500" y="501" radius="1" color="red"/>

    <mapRoad start="Z1" end="Z2"/>
    <mapRoad start="Z2" end="Z3"/>
    <mapRoad start="Z2" end="Z4"/>
    <mapRoad start="Z2" end="Z5"/>
    <mapRoad start="Z3" end="Z1"/>
    <mapRoad start="Z3" end="Z2"/>
    <mapRoad start="Z3" end="Z4"/>
    <mapRoad start="Z3" end="Z7"/>
    <mapRoad start="Z5" end="Z6"/>
    <mapRoad start="Z5" end="Z7"/>

    <printPMQuadtree/>

</commands>

=== a-blender/cmsc420/src/sample-sets/part2.public.treap.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part2in.xsd"
	pmOrder="3" spatialWidth="1024" spatialHeight="1024">

 <createCity id="1"  name="Baltimore" y="37" x="140" radius="5" color="black"/>
 <printTreap id="2"  />
 <createCity id="3"  name="Chicago" x="133" y="34" radius="5"  color="black"/>
 <printTreap id="4"  />
 <createCity id="5"  name="Atlanta" x="278" y="765" radius="5"  color="black"/>
 <printTreap id="6"  />
 <clearAll id="7"  />
</commands>

=== a-blender/cmsc420/sample-sets/part2.public.shortestPath.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:noNamespaceSchemaLocation="part2in.xsd"
 	pmOrder="3" 
 	spatialWidth="256" 
 	spatialHeight="256">
 <createCity id="1"  name="Berlin" x="128" y="128" radius="0" color="red"/>
 <createCity id="2"  name="Geneva" x="90" y="70" radius="0" color="orange"/>
 <createCity id="3"  name="Madrid" radius="0" x="45" y="50" color="yellow"/>
 <createCity id="4"  name="Andorra" x="55" color="green" y="50" radius="0" />
 <createCity id="5"  name="London" x="70" y="140" radius="0" color="blue"/>
 <createCity id="6"  name="Edinburgh" x="70" y="165" radius="0" color="blue"/>
 <createCity id="7"  name="Athens" x="200" y="40" radius="0" color="blue"/>
 <createCity id="8"  name="Varna" x="210" y="100" radius="0" color="blue"/>
 <createCity id="9"  name="Moscow" x="220" y="220" radius="0" color="blue"/>
 <createCity id="10"  name="St_Petersburg" x="225" y="225" radius="0" color="blue"/>
 <createCity id="11"  name="Stockholm" x="140" y="190" radius="0" color="blue"/>
 <createCity id="12"  name="Paris" x="94" y="98" radius="0" color="blue"/>
 <createCity id="13"  name="Zurich" x="98" y="94" radius="0" color="blue"/>
 <createCity id="14"  name="Lisbon" x="20" y="20" radius="0" color="blue"/>
 <createCity id="15"  name="Seville" x="30" y="10" radius="0" color="blue"/>
 <createCity id="16"  name="Warsaw" x="200" y="150" radius="0" color="blue"/>
 <createCity id="17"  name="Nantes" x="75" y="80" radius="0" color="blue"/>
 <createCity id="18"  name="Brussels" x="100" y="105" radius="0" color="blue"/>
 <createCity id="19"  name="Amsterdam" x="110" y="118" radius="0" color="blue"/>
 <createCity id="20"  name="Kiev" x="240" y="95" radius="0" color="blue"/>
 <createCity id="21"  name="Coppenhagen" x="120" y="140" radius="0" color="blue"/>
 <createCity id="22"  name="Prague" x="130" y="100" radius="0" color="blue"/>
 <createCity id="23"  name="Milan" x="100" y="75" radius="0" color="blue"/>
 <createCity id="24"  name="Rome" x="50" y="120" radius="0" color="blue"/>
 <createCity id="25"  name="Minsk" x="200" y="160" radius="0" color="blue"/>
 <createCity id="26"  name="Istanbul" x="250" y="20" radius="0" color="blue"/>
 <createCity id="27"  name="Belgrade" x="75" y="220" radius="0" color="blue"/>
 <createCity id="28"  name="Helsinki" x="150" y="200" radius="0" color="blue"/>
 <createCity id="29"  name="Bergen" x="120" y="200" radius="0" color="blue"/>
 <createCity id="30"  name="Stavanger" x="120" y="190" radius="0" color="blue"/>
 <createCity id="31"  name="Oslo" x="130" y="190" radius="0" color="blue"/>
 <createCity id="32"  name="Trondheim" x="130" y="200" radius="0" color="blue"/>

 <mapRoad id="33"  start="Lisbon" end="Madrid"/>
 <mapRoad id="34"  start="Madrid" end="Andorra"/>
 <mapRoad id="35"  start="Milan" end="Paris"/>
 <mapRoad id="36"  start="Milan" end="Zurich"/>
 <mapRoad id="37"  start="Milan" end="Rome"/>
 <mapRoad id="38"  start="Paris" end="Zurich"/>
 <mapRoad id="39"  start="London" end="Edinburgh"/>
 <mapRoad id="40"  start="Paris" end="Berlin"/>
 <mapRoad id="41"  start="Berlin" end="Warsaw"/>
 <mapRoad id="42"  start="Milan" end="Andorra"/>
 <mapRoad id="43"  start="Milan" end="Athens"/>
 <mapRoad id="44"  start="Athens" end="Varna"/>
 <mapRoad id="45"  start="Stockholm" end="Minsk"/>
 <mapRoad id="46"  start="Moscow" end="Stockholm"/>
 <mapRoad id="47"  start="Moscow" end="Kiev"/>
 <mapRoad id="48"  start="Varna" end="Kiev"/>
 <mapRoad id="49"  start="Moscow" end="Helsinki"/>
 <mapRoad id="50"  start="Oslo" end="Stavanger" />
 
 <shortestPath id="51"  start="Milan" end="Minsk" saveHTML="shortestPathPublic.output.fromMilanToMinsk"/>
 
 <mapRoad id="52"  start="Varna" end="Moscow"/>
 
 <shortestPath id="53"  start="London" end="London" />
 <shortestPath id="54"  start="Oslo" end="Stavanger" />
 <shortestPath id="55"  start="Warsaw" end="Athens" />
 <shortestPath id="56"  start="Varna" end="Andorra" />
 <shortestPath id="57"  start="Milan" end="Minsk" />
</commands>

=== a-blender/cmsc420/MeeshQuest/src/sample-sets/part2.public.listCities.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part2in.xsd"
 	spatialWidth="512"
 	spatialHeight="512"
 	pmOrder="3">
 <createCity id="1" name="Baltimore" y="39" x="76" radius="0" color="black"/>
 <createCity id="2" name="Chicago" x="81" y="47" radius="0"  color="black"/>
 <createCity id="3" name="Atlanta" x="84" y="33" radius="0"  color="black"/>
 <createCity id="4" name="Los_Angeles" x="118" y="33" radius="0"  color="black"/>
 <createCity id="5" name="Miami" x="80" y="25" radius="0"  color="black"/>
 <createCity id="6" name="Boston" x="71" y="42" radius="0"  color="black"/>
 <listCities id="7" sortBy="coordinate"/>
</commands>
